import { UserSession, AppConfig } from '@stacks/auth';
import { Storage } from '@stacks/storage';
import { putFileEncrypted, putFileEncryptedNot } from '../modules/gaiator';
const privateKey = '2e0f1b1b5b2dd054fcc176d5b8e82e0425cec26e555d108298a7e16a8853e7a9';
const appConfig = new AppConfig(['store_write', 'publish_data'], 'trubit');
const aFileEncrypted = 'dart03/user_data_105_encrypted.json';
const aFileEncryptedNot = 'dart03/user_data_105_encrypted_not.json';
const aData = JSON.stringify({ 'interest': 'skiing', 'age': 22, 'gender': 'male' });
const userSession = new UserSession({ appConfig });
userSession.store.getSessionData().userData = { appPrivateKey: privateKey, };
const storage = new Storage({ userSession });
const urlFileEncrypted = await putFileEncrypted({ aStorage: storage, aFileName: aFileEncrypted, aData: aData });
console.log('\n[urlFileEncrypted]=' + urlFileEncrypted);
const urlFileEncryptedNot = await putFileEncryptedNot({ aStorage: storage, aFileName: aFileEncryptedNot, aData: aData });
console.log('\n[urlFileEncryptedNot]=' + urlFileEncryptedNot);
console.log('\n' + JSON.stringify(userSession));
